<a href="https://colab.research.google.com/github/polymathkids/AdvPredModels/blob/main/HW7_AMP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Consider the following diagonal matrix:

$\begin{pmatrix} 2 & 0 & 0 & 0 & 0 & 0 \\  0 & 1.5 & 0 & 0 & 0 & 0 \\ 0 & 0 & -3 & 0 & 0 & 0 \\  0 & 0 & 0 & -1 & 0 & 0 \\ 0 & 0 & 0 & 0 & .5 & 0 \\ 0 & 0 & 0 & 0 & 0 & -.5 \\ \end{pmatrix}$

a. Is this matrix dense or sparse? Is it symmetric?

For a 6x6 matrix with 36 possible values and only 6 values that are not zero, I would consider this a sparse matrix.


b. Compute and report the eigenpairs of this matrix. Show work for at least one. Give an short explanation for why you do not need to show work for all.

In [7]:
import numpy as np

# given matrix diagonal
a_diag = np.array([2,1.5,-3,-1,.5,-.5])
# Create a diagonal matrix from the array
A = np.diag(a_diag)

#show work for at least one: 

#to calculate the eigenvalue/eigenvector of a matrix
#you first calaculate the characteristic polynomial of the matrix
#p(A) = det(lambda * I - A) where I is the Identity matrix
I = np.array([1,1,1,1,1,1])
I = np.diag(I)
print(I)


from sympy import *
l = Symbol("l") #let l represent lambda
print(l*I-A)

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]
[[I*l - 2.0 I*l I*l I*l I*l I*l]
 [I*l I*l - 1.5 I*l I*l I*l I*l]
 [I*l I*l I*l + 3.0 I*l I*l I*l]
 [I*l I*l I*l I*l + 1.0 I*l I*l]
 [I*l I*l I*l I*l I*l - 0.5 I*l]
 [I*l I*l I*l I*l I*l I*l + 0.5]]


1. Start with the 6x6 matrix A.

$A = $
$\begin{pmatrix} 2 & 0 & 0 & 0 & 0 & 0 \\  0 & 1.5 & 0 & 0 & 0 & 0 \\ 0 & 0 & -3 & 0 & 0 & 0 \\  0 & 0 & 0 & -1 & 0 & 0 \\ 0 & 0 & 0 & 0 & .5 & 0 \\ 0 & 0 & 0 & 0 & 0 & -.5 \\ \end{pmatrix}$

2. Calculate the characteristic polynomial of A, which is given by det(A - λI) = 0, where λ is an eigenvalue of A and I is the 6x6 identity matrix.

$\lambda*I - A = $
$\begin{pmatrix} \lambda - 2 & 0 & 0 & 0 & 0 & 0 \\  0 & \lambda - 1.5 & 0 & 0 & 0 & 0 \\ 0 & 0 & \lambda + 3 & 0 & 0 & 0 \\  0 & 0 & 0 & \lambda +1 & 0 & 0 \\ 0 & 0 & 0 & 0 & \lambda - .5 & 0 \\ 0 & 0 & 0 & 0 & 0 & \lambda +.5 \\ \end{pmatrix}$

$p(lambda) = det(\lambda * I - A) = $
$(\lambda - 2)(\lambda - 1.5)(\lambda + 3)(\lambda + 1)(\lambda - 0.5)(\lambda + 0.5))$

3. Solve the characteristic polynomial to find the eigenvalues λ1, λ2, ..., λn of A.

The eigenvalues then must be: 
$\lambda_1 = 2,    \lambda_2 =1.5 , \lambda_3 = -3, \lambda_4 =  -1, \lambda_5 =   0.5, \lambda_6 =-0.5$
4. For each eigenvalue λi, solve the system of linear equations $(A - \lambda_i*I)x = 0$ to find the corresponding eigenvector vi.

for $\lambda_1 = 2, v_1 = 1$
This is the same for $\lambda_2$ to $\lambda_6$

5. Normalize each eigenvector vi to have length 1

The Eigenvector is therefore the Identity matrix:

$V = $
$\begin{pmatrix} 1 & 0 & 0 & 0 & 0 & 0 \\  0 & 1 & 0 & 0 & 0 & 0 \\ 0 & 0 & 1 & 0 & 0 & 0 \\  0 & 0 & 0 & 1 & 0 & 0 \\ 0 & 0 & 0 & 0 & 1 & 0 \\ 0 & 0 & 0 & 0 & 0 & 1 \\ \end{pmatrix}$

Work is not needed for all becuase A is a diagonal matrix with the $A_{11}, A_{22}, A_{33}, A_{44}, A_{55}$ and $A_{66}$ elements equaling the corresponding $\lambda$ times the Identity matrix as the other elements of the matrix = 0. Computing the eigenvalues and eignevectors are therefore straightforward. Confirmation is shown below:

In [9]:

# compute the eigenvalues
eigenvalues, eigenvectors = np.linalg.eig(A)

# Print the eigenvalues and eigenvectors
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)


Eigenvalues: [ 2.   1.5 -3.  -1.   0.5 -0.5]
Eigenvectors:
 [[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


c. By hand, compute and report the Frobenius, Operator, and Nuclear norms of this matrix. (Math does not have to be shown if proper justification can be given for its absence)





The singular values of the matrix are $[0.5, 0.5, 1, 1.5, 2, 3]$ and are ordered from smallest to largest. Due to the matrix A being a diagonal matrix, the signular values are just the absolute values of the eignenvalues and diagonal matrix values in ordered sequence.

The Frobenius norm is the $\ell_2$ norm of the singular values $= \sqrt{\sigma_1^2 + \sigma_2^2 + \sigma_3^2}... = \sqrt{2^2 +    1.5^2 +  3^2 +  1^2 +    0.5^2 + 0.5^2} = 4.09$

The Operator norm of the matrix is the $\ell_\infty$ norm of the signular values $= max(\sigma_i) = 3$

The Nuclear norm is the $\ell_1$ norm of the singluar values $= \Sigma_i\sigma_i = \Sigma(2+1.5+3+1+.5+.5) = 8.5$ 

d. Compare the largest eigenvalue in part b to the operator norm in part c. Are they equal? Why or why not?

They are the same if you allow for taking the absolute value of the eignvalues but otherwise, the max value of the eignenvalues is 2 while the max value of the singular values is 3.

We showed that eigenvalues of the given matrix (named A) were defined as the solutions to the equation $det(A - \lambda*I) = 0$, where I is the identity matrix and $\lambda$ is a scalar. The eigenvalues of A were the roots of this polynomial, and they represent the scaling factor for the corresponding eigenvectors of A. Eigenvalues can be negative, zero, or positive, depending on the matrix A. In this case, the largest absolute value was -3 but the largest scalar value was 2.

On the other hand, the singular values of the matrix A were defined as the square roots of the eigenvalues of the matrix A^T A or AA^T. In our case with a diagonal matrix, they were the absolute values of the eigenvalues. Singular values are always non-negative real numbers. 

Since eigenvalues can be negative, zero, or positive and singluar values can only be positive, the difference in largest values is dependent on the signs of the values in the diagonal matrix A.
